import yaml
import subprocess
import time
import threading
import logging

def get_api_key_manager():  
    return ERICAPIKeyManager()

def read_yaml(file_path):  
    try:  
        with open(file_path, 'r') as file:  
            return yaml.safe_load(file)  
    except FileNotFoundError:  
        return {}

def write_yaml(file_path, data):  
    with open(file_path, 'w') as file:  
        yaml.dump(data, file, allow_unicode=True, default_flow_style=False)


KEY_DURATION = 60
APIKEYFILE = '.ericaifile'
def singleton(cls):  
    instances = {}
    lock = threading.Lock()  
    def getinstance():
        with lock:
            if cls not in instances:  
                instances[cls] = cls()  
        return instances[cls]  
    return getinstance
  
@singleton  
class ERICAPIKeyManager:

    def __init__(self):
        self._lock = threading.Lock()
        self._validtime = KEY_DURATION
        data = read_yaml(APIKEYFILE)
        if 'token' in data:
            if self._key_is_valid(data['timestamp']):
                # key is valid
                self._apikey = data['token']
                self._timestamp = data['timestamp']
                return
        # key is not valid
        self._generate_ericai_apikey()
        if self._apikey:
            print("ERICAPIKeyManager initialization ok")
        else:
            raise ValueError("Failed to generate API key on initialization")
        
    def set_validtime(self,validtime=60):
        self._validtime = validtime
  
    def _key_is_valid(self,timestamp):
        if timestamp:
            current_time = time.time()
            duration_time = current_time - timestamp
            return (duration_time < (self._validtime-1) * 60)
        return False
    
    def key_is_expired(self):
        with self._lock:
            return (not self._key_is_valid(self._timestamp))
    
    def get_ericai_apikey(self):
        with self._lock:
            if not self._key_is_valid(self._timestamp):
                self._generate_ericai_apikey()
            if self._apikey is None:  
                    raise ValueError("Failed to generate new API key")
            return self._apikey
        
    def _generate_ericai_apikey(self):
        """ericai --ericsson-access-token --fail-on-interactive-login --ericsson-force-new-access-token"""
        logging.info("Generate API Key")
        command = ["ericai","--ericsson-access-token","--fail-on-interactive-login","--ericsson-force-new-access-token"]
        try:
            result = subprocess.run(command, capture_output=True, text=True, check=True)
            print(result)
        except subprocess.CalledProcessError as e:  
            logging.error(f"Execute, returncode: {e.returncode}")  
            logging.error(f"error output: {e.output}")
            raise ValueError(f"Failed to generate API key, command: {command}")
        if result.returncode != 0:
            logging.error(f"Error executing command: {result.stderr}")  
            return
        apikey = result.stdout.strip()
        if not apikey:
            logging.error("No API key generated by the command")  
            return
        timestamp = time.time()
        data={
            'token': apikey,
            'timestamp': timestamp
        }
        self._apikey = apikey
        self._timestamp = timestamp
        write_yaml(APIKEYFILE,data)
